### ISSUE TITLE
Determine what palette limitations will be for new Pokémon sprites

### ISSUE THREAD

**Issue by emmaffiondavies** [andidavies92/pokemon-rby-dx#1]
## Overview

The most practical way to do this will be to analyse a typical battle scene and deconstruct it, while cross-referencing with GBC colour palette restrictions, in order to define what limits we will be working to when designing the new Pokémon sprite graphics.

## Purpose

Without this information, it's not realistic to ask @JackalOfTime to start designing the new pixel artwork for the Pokémon battle sprites, as the number of colours (and range of colour choices) will directly affect her design decisions.

## Tasks

* [x] Find-out how palettes are applied to each tile (i.e. how many colours each tile can have).
* [x] Use an emulator to isolate which graphics are on each layer.
* [x] Inform @JackalOfTime that she can start her design work.
* [x] Annotate (a) screenshot(s) of a deconstructed battle scene to illustrate findings.
* [x] Start a wiki for the repository.
* [x] Document findings and add them to the wiki.
* [x] Update the repo's README to reference the wiki.
* [x] File new issues for follow-up work.

## Resources

* https://en.wikipedia.org/wiki/List_of_video_game_console_palettes#Game_Boy_Color
* https://www.tvtropes.org/pmwiki/pmwiki.php/UsefulNotes/GameboyColor
* https://www.nintendo.co.uk/Support/Game-Boy-Pocket-Color/Product-information/Technical-data/Technical-data-619585.html
* https://bgb.bircd.org/pandocs.htm _(**note:** this one looks the most informative)_

## Future

* [#2 &ndash; Initial repository-tidying refactors](https://www.github.com/AmateurPanda92/pokemon-rby-dx/issues/2)
* [#3 &ndash; Define and document a workflow for creating and adding new front-facing Pokémon assets](https://www.github.com/AmateurPanda92/pokemon-rby-dx/issues/3)
* [#4 &ndash; Create and add new assets for all front-facing Pokémon graphics](https://www.github.com/AmateurPanda92/pokemon-rby-dx/issues/4)
* [#5 &ndash; Investigate whether GH Actions can be used for build verification and automatic releases](https://www.github.com/AmateurPanda92/pokemon-rby-dx/issues/5)

**Comment by emmaffiondavies** [comment]
Keep in mind that souped-up graphics data will use more RAM and storage, so that may mean that limitations have to be stricter than what the raw hardware is capable of rendering.

If there's room left in RAM and ROM at the end of development, then it may be possible to use other tricks like changing palettes during hblank to increase the number of colours for Pokémon character graphics further during battles.

**Comment by emmaffiondavies** [comment]
[This MVG video](https://www.youtube.com/watch?v=ZEJVOH6Pxkg) seems to confirm what I believed to be the case regarding colour palettes for the background and sprite layers, whereby the following limitations exist:

* Up to **8 four-colour palettes** can be attributed to _background tiles_.
* Up to **8 four-colour palettes** can be attributed to _sprite tiles_ (although in practice this is _more like 3 colours_, as _at least one "colour"_ is always used to indicate _transparent pixels_).
* Each _background tile_ can use one of its 8 four-colour palettes.
* Each _sprite tile_ can use one of its 8 four-colour palettes.

![image](https://user-images.githubusercontent.com/17612522/88446344-1fbdda80-ce21-11ea-83db-9a7291c4ab75.png)

![image](https://user-images.githubusercontent.com/17612522/88446312-e5543d80-ce20-11ea-82b0-bc36f890d6cb.png)

![image](https://user-images.githubusercontent.com/17612522/88446322-f9983a80-ce20-11ea-93a8-00338b877851.png)

**Comment by emmaffiondavies** [comment]
According to [this Wikipedia article](https://en.wikipedia.org/wiki/List_of_video_game_console_palettes#Game_Boy_Color), the colour space available for the palettes includes a total of 32,768 colours (15-bit RGB, i.e. 5 bits per colour). Of these colours, up to 56 can be displayed on screen at any one time using standard display methods, but colours like black and white are often used in multiple palettes, due to many tiles needing them, so the total number of colours displayed at any one time (without clever coding trickery) is often less than 56 due to the repeated colours. These findings tally with MVG's video above.

**Comment by emmaffiondavies** [comment]
All this is also corroborated by this specification document:
https://bgb.bircd.org/pandocs.htm#lcdcolorpalettescgbonly

**Comment by emmaffiondavies** [comment]
While conducting this research, I stumbled across a forum post reply which contained an excellent, concise overview of all the display limitations of the GBC. Within the reply was also a recommendation for further reading on the _Pan Docs_ project. Links to all of these resources can be found below:

* **Forum post reply:** https://forums.nesdev.com/viewtopic.php?t=17319#p217915
* **Legacy Pan Docs wiki:** https://gbdev.gg8.se/wiki/articles/Pan_Docs
* **Current living Pan Docs document:** https://www.gbdev.io/pandocs
* **Pan Docs GitHub repo:** [gbdev/pandocs](https://www.github.com/gbdev/pandocs)

**Comment by emmaffiondavies** [comment]
@gbdev in general appear to have a lot of great resources!

**Comment by emmaffiondavies** [comment]
Wow, ngl, this looks like a pretty fantastic community:
https://www.gbdev.io/

**Comment by emmaffiondavies** [comment]
> @andidavies92: _"According to [this Wikipedia article](https://en.wikipedia.org/wiki/List_of_video_game_console_palettes#Game_Boy_Color), the colour space available for the palettes includes a total of 32,768 colours (15-bit RGB, i.e. 5 bits per colour). Of these colours, up to 56 can be displayed on screen at any one time using standard display methods, but colours like black and white are often used in multiple palettes, due to many tiles needing them, so the total number of colours displayed at any one time (without clever coding trickery) is often less than 56 due to the repeated colours. These findings tally with MVG's video above."_

When it comes to designing the new artwork, I'd say the best approach would be to set Photoshop to use a 16-bit colour space – as only 8, 16 and 32 are available for RGB – and then we alter the existing tooling to take the PNG output from Photoshop and extract the 2-bit tile data and down-sample the palette rounding to the nearest neighbour. This gives the greatest flexibility to the artists while not risking too many colour accuracy issues.

**Comment by emmaffiondavies** [comment]
I was pretty sure already that this was the case, but I've now confirmed through an emulator by disabling each layer in turn, that all battle graphics other than attack and item animations (which are done using sprites) are displayed as background graphics, which makes life much simpler.

![Screenshot](https://user-images.githubusercontent.com/17612522/88447557-6a911f80-ce2c-11ea-9f63-ad198c23be75.png)

**Comment by emmaffiondavies** [comment]
> @andidavies92: _"When it comes to designing the new artwork, I'd say the best approach would be to set Photoshop to use a 16-bit colour space – as only 8, 16 and 32 are available for RGB – and then we alter the existing tooling to take the PNG output from Photoshop and extract the 2-bit tile data and down-sample the palette rounding to the nearest neighbour. This gives the greatest flexibility to the artists while not risking too many colour accuracy issues."_

Actually, thinking about it, it might make more sense to use a specially-designed tool to do the artwork which enforces the limitations of the platform, such as the correct colour-depth, palette definitions and only allowing the four colours from one of the 8 palettes in each tile (for which there's a handy tile grid overlay as well), such as the [Tilemap GB](https://www.github.com/bbbbbr/gimp-tilemap-gb) GIMP plugin or the **much** older (and possibly no longer working) [GBTD](http://www.devrs.com/gb/hmgd/gbtd.html).

Once we have a design that matches the requirements, we can create a full mockup of a battle scene still, to see how the finished product could foreseeably look, and then work on the tooling and modifications needed to incorporate the new designs and colours into the game.

**Comment by emmaffiondavies** [comment]
**Note:** Just while I think of it, I'd recommend that the new designs for the enemy graphics leave at least a one-pixel line of empty space at the bottom of the graphic, so that the bottom of this graphic and the top of the player's Pokémon's name text don't touch.

**Comment by emmaffiondavies** [comment]
I now have sufficient information to be able to define how the palettes will be divvied-up:

| _#_         | _Purpose_                                                                                 | Colour 1              | Colour 2                   | Colour 3                          | Colour 4                                                                         |
|:-----------:|-------------------------------------------------------------------------------------------|-----------------------|----------------------------|-----------------------------------|----------------------------------------------------------------------------------|
| _1_         | _Playfield and details (i.e. tufts of grass, sea waves, cave rocks, etc.)_                | Playfield base colour | Playfield highlight colour | Playfield shade colour            | Additional highlight or shade colour                                             |
| _2_         | _Primary menu colours_                                                                    | Black                 | White                      | Red (for Pokéball)                | Grey (for shading)                                                               |
| _3_         | _Health bar colours (smoothly transition from green, through yellow and  orange, to red)_ | Black                 | Playfield base colour      | Enemy Pokémon's health bar colour | Player's Pokémon's health bar colour                                             |
| _4_         | _Used for enemy Pokémon's outline and HUD_                                                | Black                 | Playfield base colour      | Pokémon colour 1                  | Pokémon colour 2 _or_ playfield shade colour (e.g. for Pokémon's shadow or glow) |
| _5_         | _Used for player's Pokémon outline and HUD_                                               | Black                 | Playfield base colour      | Pokémon colour 1                  | Pokémon colour 2 _or_ playfield shade colour (e.g. for Pokémon's shadow or glow) |
| _6_         | _Enemy Pokémon's primary palette_                                                         | Anything              | Anything                   | Anything                          | Anything                                                                         |
| _7_         | _Enemy Pokémon's secondary palette_                                                       | Anything              | Anything                   | Anything                          | Anything                                                                         |
| _8_         | _Player's Pokémon's palette_                                                              | Anything              | Anything                   | Anything                          | Anything                                                                         |

@JackalOfTime, could you review this table when you get a chance to make sure it: 1, makes sense; 2, is practical to work with; and 3, isn't going to stifle your creativity too much? If it is too limiting, then one thing we could do would be to abandon the different types of playfield (grass, water, cave, etc.) to free-up colours for the Pokémon themselves, but I think that'd be a unique nicety to keep if possible. I think this plan gives a nice balance of lots of different elements, rather than giving the Pokémon graphics all the love, and instead enhancing the whole experience, if that makes sense?

Once we have a spec for the palettes agreed on, I'll formalise them and document them properly on the wiki, so you can refer to them in a more accessible manner when designing the new graphics. Each 8 × 8 pixel tile can have any one of these 8 four-colour palettes attributed to them by the way.

P.s. You might want to read through all my comments on this issue to get a feel for what research was behind these decisions. Some of it will be too technical, but you should be able to get the gist of things.

**Comment by JackalOfTime** [comment]
This all looks doable to me - I agree with most of it, I don't view it as stifling the creativity as it is giving me way more to work with than before technically :3 All good my end!

**Comment by emmaffiondavies** [comment]
> @JackalOfTime _"This all looks doable to me - I agree with most of it, I don't view it as stifling the creativity as it is giving me way more to work with than before technically :3 All good my end!"_

Okay, sweet! If you crack-on with initial work on one of the three starter Pokémon's artwork then and I'll write all this up into a proper wiki article for reference.

**Comment by JackalOfTime** [comment]
Okay so I need some thoughts on the lineart that I have going, whether to do some light lineart or just leave it all black? I personally prefer the coloured line work, but I'm open to ideas, the coloured pieces just feel more polished!

Take a look at these images and see:
![Screenshot (385)](https://user-images.githubusercontent.com/68201555/94999748-5ba8b500-05b3-11eb-9a70-b994a4e0c02f.png)
![Screenshot (387)](https://user-images.githubusercontent.com/68201555/94999749-5c414b80-05b3-11eb-825a-1eaae5ae5e3c.png)
![Screenshot (386)](https://user-images.githubusercontent.com/68201555/94999751-62cfc300-05b3-11eb-82e8-7385788597c5.png)
![Screenshot (388)](https://user-images.githubusercontent.com/68201555/94999752-63685980-05b3-11eb-877f-2d2ba916c673.png)

**Comment by JackalOfTime** [comment]
![abra_line2](https://user-images.githubusercontent.com/68201555/94999766-8266eb80-05b3-11eb-9a4e-f314b1e8acbd.png)
![charmander__line2](https://user-images.githubusercontent.com/68201555/94999767-8266eb80-05b3-11eb-8783-5d58fa03a645.png)
![abra](https://user-images.githubusercontent.com/68201555/94999773-872b9f80-05b3-11eb-8d46-e57e274ee41c.png)
![charmander](https://user-images.githubusercontent.com/68201555/94999774-872b9f80-05b3-11eb-8cad-ce8f3d8cd1fa.png)

**Comment by emmaffiondavies** [comment]
Loving the direction. I don't think the edges need to necessarily be black outlines, so the ones where the outline colour can differ are preferred. These look fantastic by the way!!

Unfortunately, however, they both have waaay too many colours for the GBC to handle haha. Based on the allocation table in my previous comment, these enemy sprites have three lots of four-colour palettes available, which have to be carefully chosen and allocated to each tile in order to make best use of the limited total colours and colours per tile. I had a play around with your Charmander sprite in Photoshop to demonstrate how we might go about manually downsampling your high-colour artwork into faithful, still-colourful versions that we can get the GBC to display.

This GIF shows a screen capture of my Photoshop session's output where I've decided what the most important colours are and allocated them into the three palettes, where the tile boundaries should be in order to maximise key colour/feature retention, which palette gets allocated to each tile, made any adjustments to the base graphics in order to get the most out of each tile (e.g. nudging/expanding/shrinking elements to line them up to the grid more), and assigned palette colours to each pixel. I flick between your original and my downsampled version to illustrate the difference and how it had to be changed to meet the system's technical requirements:

![Photoshop Session Screen Capture](https://user-images.githubusercontent.com/17612522/100398682-a856bc80-3047-11eb-9338-bcb060843cdf.gif)

I hope this makes sense? One way we could approach this, so you don't have to get overly bogged-down in the technical limitations, could be for you to do the artwork as you have done above, then I'll process them by hand to meet the system requirements, and get you to review/tweak the processed version, before we sign it off?

Let me know your thoughts on all this either way.

**Comment by emmaffiondavies** [comment]
And here's how it might look on an original monochrome DMC Game Boy (if we decided to maintain backwards compatibility with it):

![image](https://user-images.githubusercontent.com/17612522/100469423-18a82100-30ce-11eb-9e1a-ba01cfeac4ba.png)

**Comment by emmaffiondavies** [comment]
I had a go at adding the graphics to the ROM and running in DMG mode in an emulator, and it really doesn't look great in the original palette, so I definitely think we should still ditch DMG compat, otherwise we risk compromising on the quality of what we could do with the graphics on the GBC, which is the main point of this project after all.

![2020-12-12 (1)](https://user-images.githubusercontent.com/17612522/103176001-4bc50800-4866-11eb-8a9b-b351ad167af2.png)

**Comment by emmaffiondavies** [comment]
I made this annotated image a while ago (and forgot to post it here) which illustrates how the [new palette allocations](https://www.github.com/AmateurPanda92/pokemon-rby-dx/issues/1#issuecomment-663807207) would/could be applied to the background tiles in a typical battle scene:

![Battle Palette Allocations](https://user-images.githubusercontent.com/17612522/103176127-048b4700-4867-11eb-9ace-58751c40099a.png)

The colours in the image pertain to the [palette table](https://www.github.com/AmateurPanda92/pokemon-rby-dx/issues/1#issuecomment-663807207) palette numbers as follows:

* **Palette 1** &ndash; _pink_.
* **Palette 2** &ndash; _red_.
* **Palette 3** &ndash; _orange_.
* **Palette 4** &ndash; _yellow_.
* **Palette 5** &ndash; _green_.
* **Palette 6** &ndash; _blue_.
* **Palette 7** &ndash; _violet_.
* **Palette 8** &ndash; _indigo_.

**Comment by emmaffiondavies** [comment]
I've started a wiki for the repo: https://www.github.com/AmateurPanda92/pokemon-rby-dx/wiki

**Comment by emmaffiondavies** [comment]
I've updated the repo's [README](https://github.com/AmateurPanda92/pokemon-rby-dx/blob/main/README.md) with links to the new wiki and its various sections.

**Comment by emmaffiondavies** [comment]
I've filed new issues #2, #3, #4 and #5 for follow-up work relating to this issue, so this one can now be closed.
